grant execute on GetTransactionById to admin_user;
grant execute on GetCardById to admin_user;
grant execute on AddLoanType to admin_user;
grant execute on UpdateLoanType to admin_user;
grant execute on DeleteLoanType to admin_user;
grant execute on AddNewCurrency to admin_user;
grant execute on UpdateCurrencyInfo to admin_user;
grant execute on GetClientInfoById to admin_user;
grant execute on GetClientAccountById to admin_user;
grant execute on GetClientLoansById to admin_user;
grant execute on GetAllClientCardsById to admin_user;
grant execute on AddLoanTransaction to admin_user;
grant execute on UpdateClientCardStatus to admin_user;
grant execute on GetAllClientsAccounts to admin_user;
grant execute on GetAllClientInfos to admin_user;
grant execute on GetAllClientCards to admin_user;
grant execute on ProcessLoanApplication to admin_user;
grant execute on GetLoanApplications to admin_user;
grant execute on AddAccountToClient to admin_user;
grant execute on CloseClientAccount to admin_user;
grant execute on GetAllCurrencies to admin_user;
grant execute on GetClientProfileInfo to admin_user;
grant execute on GetAllClientSupportRequests to admin_user;
grant execute on GetAllCreditTypes to admin_user;
grant execute on GetListOfClientAccountsByClientId to admin_user;
grant execute on DeleteClientProfile to admin_user;
grant execute ON AddBankCard to admin_user;
grant execute ON DeleteBankCard to admin_user;

grant execute ON GetAllCurrencies to admin_user;
grant execute ON GetAllAppUsers to admin_user;
grant execute ON GetAllUserAccounts to admin_user;
grant execute ON GetAllUserProfiles to admin_user;
grant execute ON GetAllUserSupportRequests to admin_user;
grant execute ON GetAllCurrencyExchangeRates to admin_user;
grant execute ON GetAllAccountTransactions to admin_user;
grant execute ON GetAllCards to admin_user;
grant execute ON GetAllCreditTypes to admin_user;
grant execute ON GetAllPaymentServices to admin_user;
grant execute ON GetAllCredits to admin_user;


CREATE OR REPLACE SYNONYM admin_user.GetTransactionById_Syn FOR GetTransactionById;
CREATE OR REPLACE SYNONYM admin_user.GetCardById_Syn FOR GetCardById;
CREATE OR REPLACE SYNONYM admin_user.AddLoanType_Syn FOR AddLoanType;
CREATE OR REPLACE SYNONYM admin_user.UpdateLoanType_Syn FOR UpdateLoanType;
CREATE OR REPLACE SYNONYM admin_user.DeleteLoanType_Syn FOR DeleteLoanType;
CREATE OR REPLACE SYNONYM admin_user.AddNewCurrency_Syn FOR AddNewCurrency;
CREATE OR REPLACE SYNONYM admin_user.UpdateCurrencyInfo_Syn FOR UpdateCurrencyInfo;
CREATE OR REPLACE SYNONYM admin_user.GetClientInfoById_Syn FOR GetClientInfoById;
CREATE OR REPLACE SYNONYM admin_user.GetClientAccountById_Syn FOR GetClientAccountById;
CREATE OR REPLACE SYNONYM admin_user.GetClientLoansById_Syn FOR GetClientLoansById;
CREATE OR REPLACE SYNONYM admin_user.GetAllClientCardsById_Syn FOR GetAllClientCardsById;
CREATE OR REPLACE SYNONYM admin_user.AddLoanTransaction_Syn FOR AddLoanTransaction;
CREATE OR REPLACE SYNONYM admin_user.UpdateClientCardStatus_Syn FOR UpdateClientCardStatus;
CREATE OR REPLACE SYNONYM admin_user.GetAllClientsAccounts_Syn FOR GetAllClientsAccounts;
CREATE OR REPLACE SYNONYM admin_user.GetAllClientInfos_Syn FOR GetAllClientInfos;
CREATE OR REPLACE SYNONYM admin_user.GetAllClientCards_Syn FOR GetAllClientCards;
CREATE OR REPLACE SYNONYM admin_user.ProcessLoanApplication_Syn FOR ProcessLoanApplication;
CREATE OR REPLACE SYNONYM admin_user.GetLoanApplications_Syn FOR GetLoanApplications;
CREATE OR REPLACE SYNONYM admin_user.AddAccountToClient_Syn FOR AddAccountToClient;
CREATE OR REPLACE SYNONYM admin_user.CloseClientAccount_Syn FOR CloseClientAccount;
CREATE OR REPLACE SYNONYM admin_user.GetAllCurrencies_Syn FOR GetAllCurrencies;
CREATE OR REPLACE SYNONYM admin_user.GetClientProfileInfo_Syn FOR GetClientProfileInfo;
CREATE OR REPLACE SYNONYM admin_user.GetAllClientSupportRequests_Syn FOR GetAllClientSupportRequests;
CREATE OR REPLACE SYNONYM admin_user.GetAllCreditTypes_Syn FOR GetAllCreditTypes;
CREATE OR REPLACE SYNONYM admin_user.GetListOfClientAccountsByClientId_Syn FOR GetListOfClientAccountsByClientId;
CREATE OR REPLACE SYNONYM admin_user.DeleteClientProfile_Syn FOR DeleteClientProfile;
CREATE OR REPLACE SYNONYM admin_user.AddBankCard_Syn FOR AddBankCard;
CREATE OR REPLACE SYNONYM admin_user.DeleteBankCard_Syn FOR DeleteBankCard;

CREATE OR REPLACE SYNONYM admin_user.GetAllCurrencies_Syn FOR GetAllCurrencies;
CREATE OR REPLACE SYNONYM admin_user.GetAllAppUsers_Syn FOR GetAllAppUsers;
CREATE OR REPLACE SYNONYM admin_user.GetAllUserAccounts_Syn FOR GetAllUserAccounts;
CREATE OR REPLACE SYNONYM admin_user.GetAllUserProfiles_Syn FOR GetAllUserProfiles;
CREATE OR REPLACE SYNONYM admin_user.GetAllUserSupportRequests_Syn FOR GetAllUserSupportRequests;
CREATE OR REPLACE SYNONYM admin_user.GetAllCurrencyExchangeRates_Syn FOR GetAllCurrencyExchangeRates;
CREATE OR REPLACE SYNONYM admin_user.GetAllAccountTransactions_Syn FOR GetAllAccountTransactions;
CREATE OR REPLACE SYNONYM admin_user.GetAllCards_Syn FOR GetAllCards;
CREATE OR REPLACE SYNONYM admin_user.GetAllCreditTypes_Syn FOR GetAllCreditTypes;
CREATE OR REPLACE SYNONYM admin_user.GetAllPaymentServices_Syn FOR GetAllPaymentServices;
CREATE OR REPLACE SYNONYM admin_user.GetAllCredits_Syn FOR GetAllCredits;